<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>Osiris</AssemblyName>
    <RootNamespace>Osiris</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>..\..\assets\Osiris.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
